version: '3.5'

services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/var/www/html
            - ./docker/images/php81/files/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        ports:
            - "6050:8000"
        links:
            - postgresql
        working_dir: /var/www/html
    postgresql:
        image: postgres:14-alpine
        ports:
            - "5427:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: clever
        volumes:
            - ./docker/images/postgres/files/postgresql.conf:/etc/postgresql.conf
        command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
